version: 2
jobs:
  build:
    docker:
      - image: abronan/rust-circleci:latest
    steps:
      - checkout
      - restore_cache:
          key: project-cache
      - run:
          name: Stable Build
          command: |
            cd lollygag_ext/lollygag
            rustup run stable rustc --version --verbose
            rustup run stable cargo --version --verbose
            rustup run stable cargo build
      - run:
          name: Test
          command: |
            cd lollygag_ext/lollygag
            rustup run stable cargo test
      - save_cache:
          key: project-cache
          paths:
            - "~/.cargo"
            - "./target"

workflows:
  version: 2
  build_rust_standalone:
    jobs:
      - build
