version: 2
jobs:
  build-rust-standalone:
    docker:
      - image: abronan/rust-circleci:latest
    steps:
      - checkout
      - restore_cache:
          key: project-cache
      - run:
          name: Stable Build
          command: |
            cd lollygag_ext/lollygag
            rustup run stable rustc --version --verbose
            rustup run stable cargo --version --verbose
            rustup run stable cargo build
      - run:
          name: Test
          command: |
            cd lollygag_ext/lollygag
            rustup run stable cargo test
      - save_cache:
          key: project-cache
          paths:
            - "~/.cargo"
            - "lollygag_ext/lollygag/target"
  build-and-test-extension:
    docker:
      - image: circleci/python:3.6.2
    steps:
      - checkout
      - restore_cache:
          key: py-ext-cache
      - run:
          name: Setup Rust
          command: |
            curl -SsL "https://sh.rustup.rs/" | sh -s -- -y --default-toolchain=nightly
            export PATH=$PATH:$HOME/.cargo/bin
            cargo --version
      - run:
          name: Create Virtual Env
          command: |
            python3 -m venv env
            source env/bin/activate
      - run:
          name: Install lollygag
          command: |
            export PATH=$PATH:$HOME/.cargo/bin
            cargo --version
            source env/bin/activate
            pip install .[ci]
      - run:
          name: Test lollygag
          command: |
            source env/bin/activate
            pytest
      - save_cache:
          key: py-ext-cache
          paths:
            - "~/.cargo"
            - "lollygag_ext/lollygag/target"
            - "lollygag_ext/py_interface/target"
            - "./env"

  deploy_to_pypi:
    docker:
      - image: circleci/python:3.6.2
    steps:
      - checkout
      - restore_cache:
          key: py-ext-cache
      - run:
          name: Install Rust
          command: curl -SsL "https://sh.rustup.rs/" | sh -s -- -y --default-toolchain=nightly
      - run:
          name: Verify version
          command: |
            source env/bin/activate
            python setup.py verify
      - run:
          name: Build packages
          command: |
            export PATH=$PATH:$HOME/.cargo/bin
            cargo --version
            source env/bin/activate
            pip install wheel
            # python setup.py bdist_wheel # Linux wheels are not yet supported on PyPi
            python setup.py sdist
      - run:
          name: Init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = snorrwe" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
      - run:
          name: Upload to PyPi
          command: |
            source env/bin/activate
            pip install twine
            twine upload dist/*

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build-rust-standalone:
          filters:
            tags:
              only: /.*/
      - build-and-test-extension:
          filters:
            tags:
              only: /.*/
      - deploy_to_pypi:
          requires:
            - build-rust-standalone
            - build-and-test-extension
          filters:
            tags:
              only: /\d+(\.\d+){2}.*/
            branches:
              ignore: /.*/
