version: 2
jobs:
  build-rust-standalone:
    docker:
      - image: abronan/rust-circleci:latest
    steps:
      - checkout
      - restore_cache:
          key: project-cache
      - run:
          name: Stable Build
          command: |
            cd lollygag_ext/lollygag
            rustup run stable rustc --version --verbose
            rustup run stable cargo --version --verbose
            rustup run stable cargo build
      - run:
          name: Test
          command: |
            cd lollygag_ext/lollygag
            rustup run stable cargo test
      - save_cache:
          key: project-cache
          paths:
            - "~/.cargo"
            - "./target"
  build-and-test-extension:
    docker:
      - image: circleci/python:3.6.2
    steps:
      - run:
          name: Setup Rust
          command: |
            curl -SsL "https://sh.rustup.rs/" | sh -s -- -y --default-toolchain=nightly
            export PATH=$PATH:$HOME/.cargo/bin
      - checkout
      - run:
          name: Install lollygag
          command: |
            pip install setuptools_rust
            pip install .
      - run:
          name: Test lollygag
          command: pytest

workflows:
  version: 2
  build_rust_standalone:
    jobs:
      - build-rust-standalone
  build-and-test-extension:
    jobs:
      - build-and-test-extension
