[package]
name = "lollygag_ext"
version = "0.1.0"
authors = ["Daniel Kiss <littlesnorrboy@gmail.com>"]

[lib]
name = "lollygag_ext"
crate-type = ["cdylib"]

[dependencies]
lollygag = {path = "../lollygag"}
cpython = "0.2"
html5ever = "*"
